# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#Setup the database
- script: "docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Rand0mP4$s11' -d -p 1433:1433 --name MSSQLSERVER -d mcr.microsoft.com/mssql/server:2019-latest"
  displayName: 'Set up a simple docker based MSSQL database'
- script: 'pwd'
  displayName: 'get pwd'


#Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'


#UnitTest

#IntegrationTests

#DefaultChecks

#Publish Artifacts
