# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#Setup the database
#- script: 'wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -'
#- script: 'sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"'
#- script: 'apt update && apt install -y mssql-server'
#  displayName: 'Installing MSSQL on the build agent'
#- script: 'sudo /opt/mssql/bin/mssql-conf setup'
- script: 'whoami;sudo id'
  displayName: 'Linux deets'

#Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'


#UnitTest

#IntegrationTests

#DefaultChecks

#Publish Artifacts
