- hosts: localhost
  remote_user:  vsts
  become: yes
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_password: "Rand0mP4$s11"
    mssql_edition: Developer
    mssql_tcp_port: 1433
    mssql_ip_address: "{{ ansible_default_ipv4.address }}"
  roles:
    - microsoft.sql.server
