- hosts: 127.0.0.1
  connection:  local
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_password: "Rand0mP4$s11"
    mssql_edition: Developer
  roles:
    - server
  tasks:
    - name: Create the db
      shell:
        cmd:  "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Rand0mP4$s11' -i DB.sql;"

    - name: Create the table
      shell:
        cmd:  "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Rand0mP4$s11' -i Sale.sql;"
