USE [master]
GO

/****** Object:  Database [DevOpsChallenge]    Script Date: 2/26/2022 9:56:35 AM ******/
CREATE DATABASE [DevOpsChallenge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DevOpsChallenge', FILENAME = N'/var/opt/mssql/data/DevOpsChallenge_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DevOpsChallenge_log', FILENAME = N'/var/opt/mssql/data/DevOpsChallenge_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DevOpsChallenge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DevOpsChallenge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET ARITHABORT OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DevOpsChallenge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DevOpsChallenge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DevOpsChallenge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DevOpsChallenge] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DevOpsChallenge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET RECOVERY FULL 
GO

ALTER DATABASE [DevOpsChallenge] SET  MULTI_USER 
GO

ALTER DATABASE [DevOpsChallenge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DevOpsChallenge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DevOpsChallenge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DevOpsChallenge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DevOpsChallenge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DevOpsChallenge] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DevOpsChallenge] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DevOpsChallenge] SET  READ_WRITE 
GO


