USE [master]
GO

/****** Object:  Database [Sale]    Script Date: 2/26/2022 9:56:35 AM ******/
CREATE DATABASE [Sale]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sale', FILENAME = N'/var/opt/mssql/data/Sale_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sale_log', FILENAME = N'/var/opt/mssql/data/Sale_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sale].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sale] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sale] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sale] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sale] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sale] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sale] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sale] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sale] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sale] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sale] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sale] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sale] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sale] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sale] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sale] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Sale] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sale] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sale] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sale] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sale] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sale] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Sale] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sale] SET RECOVERY FULL 
GO

ALTER DATABASE [Sale] SET  MULTI_USER 
GO

ALTER DATABASE [Sale] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sale] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sale] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sale] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Sale] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Sale] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Sale] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Sale] SET  READ_WRITE 
GO


