USE [DevOpsChallenge]
GO

/****** Object:  Table [dbo].[Sale]    Script Date: 2/26/2022 9:48:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sale](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TransactionId] [nvarchar](32) NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[Amount] [float] NOT NULL,
	[Notes] [nvarchar](256) NULL,
 CONSTRAINT [PK_Sale] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


